name: calling-actions-with-actions
run-name: say hello world and list directory
on:
  push:
    branches:
      - 'actions_actions_test'
jobs:
  calling-reusable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MarinEstrada/reusable-workflows/.github/workflows/hello-world.yaml@actions_on_actions
      - uses: MarinEstrada/reusable-workflows/.github/workflows/list-non-hidden.yaml@actions_on_actions
      - uses: MarinEstrada/reusable-workflows/.github/workflows/learn-github-actions.yaml@actions_on_actions
